# Generated by Django 3.0.2 on 2020-02-18 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeimysql1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationinmovie',
            old_name='station_cd',
            new_name='station_service_code',
        ),
        migrations.RenameField(
            model_name='stationinmovie',
            old_name='station_name',
            new_name='station_service_name',
        ),
        migrations.AlterField(
            model_name='station',
            name='pref_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekimeimysql1.Prefecture', verbose_name='都道府県'),
        ),
    ]
