# Generated by Django 3.0.2 on 2020-02-18 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeimysql1', '0004_delete_stationinmovie'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationInMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_movie', models.IntegerField()),
                ('station_service_name', models.CharField(max_length=200)),
                ('non_line', models.BooleanField(default=False, verbose_name='路線不定')),
                ('back_rel', models.IntegerField(default=1, verbose_name='前駅との関係')),
                ('movie_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekimeimysql1.Part')),
                ('station_service_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='駅名', to='ekimeimysql1.StationService', to_field='station_service_code')),
            ],
        ),
    ]
