# Generated by Django 3.0.2 on 2020-04-25 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeimysql1', '0005_stationinmovie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.IntegerField(default=0)),
                ('country_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='MovieCategory',
        ),
        migrations.RenameField(
            model_name='stationinmovie',
            old_name='id_in_movie',
            new_name='id_in_part',
        ),
        migrations.RenameField(
            model_name='stationinmovie',
            old_name='station_service_name',
            new_name='station_sung_name',
        ),
        migrations.RemoveField(
            model_name='lineservice',
            name='pref_codes',
        ),
        migrations.AddField(
            model_name='artist',
            name='namerb',
            field=models.CharField(blank=True, max_length=200, verbose_name='アーティスト名カナ'),
        ),
        migrations.AddField(
            model_name='company',
            name='area_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='地域'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='会社色'),
        ),
        migrations.AddField(
            model_name='company',
            name='sort_by_area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地域ごとの並び順'),
        ),
        migrations.AddField(
            model_name='lineservice',
            name='line_color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='路線カラー'),
        ),
        migrations.AddField(
            model_name='movie',
            name='up_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='データベース更新日時'),
        ),
        migrations.AddField(
            model_name='station',
            name='pref_cd_old',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='都道府県コード（旧）'),
        ),
        migrations.AddField(
            model_name='stationinmovie',
            name='is_sung',
            field=models.BooleanField(default=True, verbose_name='歌唱されているか(同じ駅が重複している場合は偽)'),
        ),
        migrations.AddField(
            model_name='stationservice',
            name='numbering_head',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ナンバリング接頭辞'),
        ),
        migrations.AddField(
            model_name='stationservice',
            name='numbering_middle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ナンバリングハイフン'),
        ),
        migrations.AddField(
            model_name='stationservice',
            name='station_color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='駅カラー'),
        ),
        migrations.AddField(
            model_name='vocal',
            name='namerb',
            field=models.CharField(blank=True, max_length=200, verbose_name='ボーカル名カナ'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='song',
            field=models.ManyToManyField(blank=True, to='ekimeimysql1.Song', verbose_name='使用楽曲'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vocal',
            field=models.ManyToManyField(blank=True, to='ekimeimysql1.Vocal', verbose_name='使用ボーカル'),
        ),
        migrations.AlterField(
            model_name='name',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_name', to='ekimeimysql1.Creator', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_song',
            field=models.ManyToManyField(blank=True, to='ekimeimysql1.Song', verbose_name='使用楽曲'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_vocal',
            field=models.ManyToManyField(blank=True, to='ekimeimysql1.Vocal', verbose_name='使用ボーカル'),
        ),
        migrations.AlterField(
            model_name='prefecture',
            name='pref_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='station',
            name='pref_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekimeimysql1.Prefecture', verbose_name='所在地'),
        ),
        migrations.AlterField(
            model_name='stationinmovie',
            name='station_service_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekimeimysql1.StationService', to_field='station_service_code'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.IntegerField(default=0)),
                ('region_name', models.CharField(max_length=200)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ekimeimysql1.Country', verbose_name='国')),
            ],
        ),
        migrations.AddField(
            model_name='prefecture',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ekimeimysql1.Region', verbose_name='地方'),
        ),
    ]
