# Generated by Django 3.0.2 on 2020-04-29 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeimysql1', '0007_lineservice_pref_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BelongsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='所属カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='NameCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='名称カテゴリー')),
            ],
        ),
        migrations.AlterField(
            model_name='stationinmovie',
            name='is_sung',
            field=models.BooleanField(default=True, verbose_name='歌唱されているか(前駅と同一の歌唱の場合は偽)'),
        ),
        migrations.CreateModel(
            name='StationServiceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name_history', models.CharField(blank=True, max_length=200, null=True, verbose_name='駅名')),
                ('line_service_name_history', models.CharField(blank=True, max_length=200, null=True, verbose_name='路線名(運行系統)')),
                ('numbering_head_history', models.CharField(blank=True, max_length=200, null=True, verbose_name='ナンバリング接頭辞')),
                ('numbering_symbol_history', models.CharField(blank=True, max_length=200, null=True, verbose_name='路線記号')),
                ('numbering_middle_history', models.CharField(blank=True, max_length=200, null=True, verbose_name='ナンバリングハイフン')),
                ('numbering_number_history', models.CharField(blank=True, max_length=200, null=True, verbose_name='駅番号')),
                ('sort_by_line_service_history', models.IntegerField(blank=True, default=0, null=True, verbose_name='路線(運行系統)ごとの並び順')),
                ('station_color_history', models.CharField(blank=True, max_length=100, null=True, verbose_name='駅カラー')),
                ('line_service_code_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ekimeimysql1.LineService', to_field='line_service_code', verbose_name='路線コード(運行系統)')),
                ('station_service_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ekimeimysql1.StationService', to_field='station_service_code', verbose_name='駅コード(運行系統)')),
            ],
        ),
        migrations.AddField(
            model_name='line',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ekimeimysql1.BelongsCategory', verbose_name='所属カテゴリー'),
        ),
        migrations.AddField(
            model_name='lineservice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ekimeimysql1.BelongsCategory', verbose_name='所属カテゴリー'),
        ),
        migrations.AddField(
            model_name='station',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ekimeimysql1.NameCategory', verbose_name='名称カテゴリー'),
        ),
        migrations.AddField(
            model_name='stationservice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ekimeimysql1.NameCategory', verbose_name='名称カテゴリー'),
        ),
    ]
