# Generated by Django 3.0.2 on 2020-04-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeimysql1', '0008_auto_20200429_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationservice',
            name='station_service_group_code',
            field=models.IntegerField(default=0, unique=True, verbose_name='駅コード(運行系統)グループ'),
        ),
    ]
