# Generated by Django 3.0.2 on 2020-04-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeimysql1', '0009_stationservice_station_service_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationservice',
            name='station_service_group_code',
            field=models.IntegerField(default=0, verbose_name='駅コード(運行系統)グループ'),
        ),
    ]
