# Generated by Django 3.0.2 on 2020-04-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeimysql1', '0010_auto_20200429_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationservice',
            name='station_service_group_code',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='駅コード(運行系統)グループ'),
        ),
    ]
