# Generated by Django 3.0.2 on 2020-04-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeimysql1', '0012_remove_stationservice_station_service_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationservice',
            name='station_service_group_code',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='駅コード(運行系統)グループ'),
        ),
    ]
