# Generated by Django 3.0.2 on 2020-04-30 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeimysql1', '0003_auto_20200430_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_company', to='ekimeimysql1.Company', verbose_name='事業者コード[id]'),
        ),
        migrations.AddField(
            model_name='lineservice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_service_company', to='ekimeimysql1.Company', verbose_name='事業者コード[id]'),
        ),
        migrations.AddField(
            model_name='lineservice',
            name='line',
            field=models.ManyToManyField(blank=True, related_name='line_service_line', to='ekimeimysql1.Line', verbose_name='路線コード(正式)[id]'),
        ),
        migrations.AddField(
            model_name='station',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_line', to='ekimeimysql1.Line', verbose_name='路線コード[id]'),
        ),
        migrations.AlterField(
            model_name='line',
            name='company_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_company_code_old', to='ekimeimysql1.Company', to_field='company_code', verbose_name='事業者コード[code]'),
        ),
        migrations.AlterField(
            model_name='lineservice',
            name='company_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_service_company_code_old', to='ekimeimysql1.Company', to_field='company_code', verbose_name='事業者コード[code]'),
        ),
        migrations.AlterField(
            model_name='lineservice',
            name='line_code',
            field=models.ManyToManyField(blank=True, related_name='line_service_line_code_old', to='ekimeimysql1.Line', verbose_name='路線コード(正式)[code]'),
        ),
        migrations.AlterField(
            model_name='station',
            name='line_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_line_code_old', to='ekimeimysql1.Line', to_field='line_code', verbose_name='路線コード[code]'),
        ),
        migrations.AlterField(
            model_name='stationservice',
            name='line_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_service_line_service', to='ekimeimysql1.LineService', verbose_name='路線コード(運行系統)[id]'),
        ),
        migrations.AlterField(
            model_name='stationservice',
            name='line_service_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_service_line_service_code_old', to='ekimeimysql1.LineService', to_field='line_service_code', verbose_name='路線コード(運行系統)[code]'),
        ),
        migrations.AlterField(
            model_name='stationservice',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_service_station', to='ekimeimysql1.Station', verbose_name='駅コード(正式)[id]'),
        ),
        migrations.AlterField(
            model_name='stationservice',
            name='station_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_service_station_code_old', to='ekimeimysql1.Station', to_field='station_code', verbose_name='駅コード(正式)[code]'),
        ),
    ]
