# Generated by Django 3.0.2 on 2020-04-30 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeimysql1', '0005_auto_20200430_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationinmovie',
            name='station_service_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekimeimysql1.StationService', to_field='station_service_code'),
        ),
    ]
