# Generated by Django 3.0.2 on 2020-04-30 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeimysql1', '0006_auto_20200430_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationinmovie',
            name='station_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_in_movie_station_service', to='ekimeimysql1.StationService'),
        ),
        migrations.AlterField(
            model_name='stationinmovie',
            name='station_service_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_in_movie_station_service_code_old', to='ekimeimysql1.StationService', to_field='station_service_code'),
        ),
    ]
