# Generated by Django 3.0.2 on 2020-04-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeimysql1', '0006_auto_20200426_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineservice',
            name='pref_codes',
            field=models.ManyToManyField(blank=True, to='ekimeimysql1.Prefecture'),
        ),
    ]
