# Generated by Django 3.0.2 on 2020-05-04 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeimysql1', '0007_auto_20200430_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='channel_main_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_main_name', to='ekimeimysql1.Name', verbose_name='チャンネル名義'),
        ),
        migrations.AlterField(
            model_name='part',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='簡易説明'),
        ),
    ]
