# Generated by Django 3.0.2 on 2020-05-04 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeimysql1', '0008_auto_20200504_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='cv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekimeimysql1.Artist', verbose_name='担当声優'),
        ),
    ]
