# Generated by Django 3.0.2 on 2020-05-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeimysql1', '0009_artist_cv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('namerb', 'name')},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('namerb', 'name')},
        ),
        migrations.AlterModelOptions(
            name='vocal',
            options={'ordering': ('namerb', 'name')},
        ),
        migrations.AddField(
            model_name='artist',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_artist_related_+', to='ekimeimysql1.Artist', verbose_name='関連アーティスト'),
        ),
    ]
