# Generated by Django 3.0.2 on 2020-05-05 12:40

from django.db import migrations, models
import ekimeimysql1.models


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeimysql1', '0011_auto_20200505_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='line_code',
            field=models.IntegerField(default=ekimeimysql1.models.get_next_line, unique=True, verbose_name='路線コード'),
        ),
        migrations.AlterField(
            model_name='line',
            name='railway_type_name',
            field=models.CharField(default='11', max_length=100, verbose_name='鉄道種別'),
        ),
        migrations.AlterField(
            model_name='lineservice',
            name='line_service_code',
            field=models.CharField(default=ekimeimysql1.models.get_next_lineservice, max_length=10, unique=True, verbose_name='路線コード(運行系統)'),
        ),
        migrations.AlterField(
            model_name='station',
            name='railway_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='鉄道種別'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_code',
            field=models.IntegerField(default=ekimeimysql1.models.get_next_station, unique=True, verbose_name='駅コード'),
        ),
        migrations.AlterField(
            model_name='stationservice',
            name='station_service_code',
            field=models.IntegerField(default=ekimeimysql1.models.get_next_stationservice, unique=True, verbose_name='駅コード(運行系統)'),
        ),
    ]
