# Generated by Django 3.0.2 on 2020-05-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekimeimysql1', '0013_auto_20200510_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieUpdateInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_create', models.CharField(choices=[('C', '新規登録'), ('U', '更新')], default='C', max_length=1, verbose_name='新規登録か更新か')),
                ('reg_date', models.DateTimeField(blank=True, verbose_name='登録・更新日時')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekimeimysql1.Movie', to_field='main_id')),
            ],
        ),
    ]
