# Generated by Django 3.0.2 on 2020-04-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datanewsql', '0002_auto_20200425_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='up_data',
            new_name='up_date',
        ),
        migrations.RenameField(
            model_name='stationinmovie',
            old_name='station_cd',
            new_name='station_service_code',
        ),
    ]
